force-app/main/default/objects/MockHTTPSetting__mdt/MockHTTPSetting__mdt.object-meta.xml
<CustomObject>
    <label>MockHTTPSetting</label>
    <pluralLabel>MockHTTPSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/MockHTTPSetting__mdt/fields/HandlerInputs__c.field-meta.xml
<CustomField>
    <fullName>HandlerInputs__c</fullName>
    <description>JSON values for input</description>
    <label>HandlerInputs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HTTPMockStaticResourceLoader.cls
public class HTTPMockStaticResourceLoader implements HttpRequestController, MockHttpRequestController {
    
    private MockHTTPSetting__mdt mocksettings;
    
	public HttpResponseContext execute() {		        
        
        InputSetting inputs = (InputSetting) JSON.deserialize(this.mocksettings.HandlerInputs__c, InputSetting.class);        
        
        //refactor to another method
        HttpResponse response = new HttpResponse();
        response.setBody(JSON.serialize(inputs)); //change to read static resource
        response.setStatusCode(200);
        return new HttpResponseContext(response);
    }
    
    public void setMockHTTPSettings(MockHTTPSetting__mdt setting) {
        this.mockSettings = setting;
    }

    private class InputSetting {
    	public String StaticResourceName;        
    }
   
}