force-app/main/default/objects/MockHTTPSetting__mdt/MockHTTPSetting__mdt.object-meta.xml
<CustomObject>
    <label>MockHTTPSetting</label>
    <pluralLabel>MockHTTPSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/MockHTTPSetting__mdt/fields/EndPointMatchPattern__c.field-meta.xml
<CustomField>
    <fullName>EndPointMatchPattern__c</fullName>
    <label>End Point Match Pattern</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MockHTTPSetting__mdt/fields/HandlerInputs__c.field-meta.xml
<CustomField>
    <fullName>HandlerInputs__c</fullName>
    <description>JSON values for input</description>
    <label>HandlerInputs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MockHTTPSetting__mdt/fields/HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>HTTPMethod__c</fullName>
    <label>HTTPMethod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MockHTTPSetting__mdt/fields/MockHandlerClass__c.field-meta.xml
<CustomField>
    <fullName>MockHandlerClass__c</fullName>
    <label>Mock Handler Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HttpRequestControllerFactory.cls
public class HttpRequestControllerFactory {

    private static List<MockHTTPSetting__mdt> mockhandlers;
    
    static {
        mockhandlers = [SELECT id, EndPointMatchPattern__c, 
						MockHandlerClass__c, HTTPMethod__c, HandlerInputs__c
                        FROM MockHTTPSetting__mdt
                        WHERE Active__c = true
                       ];
    }
    
    public static HttpRequestController getHttpController(HttpRequestContext requestctx) {    
        return getController(requestctx);
    }

    private static HttpRequestController getController(HttpRequestContext requestctx) {
        MockHTTPSetting__mdt mockSetting = findMockController(requestctx);
        
        if (mockSetting != null) {
            return createMockController(mockSetting);
        }        
        return new HttpRequestControllerOutbound(requestctx);
    }
    
    private static MockHTTPSetting__mdt findMockController(HttpRequestContext requestctx) {
        for (MockHTTPSetting__mdt mockSetting : mockHandlers) {			
            if (requestctx.getMethod() == mockSetting.HTTPMethod__c                 
                && isPatternMatch(mockSetting.EndPointMatchPattern__c, requestctx.getEndPoint())) {
                	
               return mockSetting;
            }
        }
        return null;
    }
    
    private static Boolean isPatternMatch(String pattern, String endpoint) {        
        //change to match using regex - simple match for the moment.        
       	return endPoint.contains(pattern);
    }
    
    private static HttpRequestController createMockController(MockHTTPSetting__mdt mockSetting ) {
        Object obj = getInstance(mockSetting.MockHandlerClass__c);
        
        if (!isControllerType(obj) || !isMockControllerType(obj)) {
            return null; //throw exception etc
        }            
        
        MockHttpRequestController ctl = (MockHttpRequestController) obj;
        ctl.setMockHTTPSettings(mockSetting);
        return (HttpRequestController) ctl;
    }
        
    private static Boolean isControllerType(Object obj) {
        if (obj != null && obj instanceof HttpRequestController) {
            return true;
        }
        return false;
    }

    private static Boolean isMockControllerType(Object obj) {
        if (obj != null && obj instanceof MockHttpRequestController) {
            return true;
        }
        return false;
    }

    private static Object getInstance(String className) {
        Type t = Type.forName(className);
        return t.newInstance();
    }
}